config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'galleries/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users

  resources :galleries do
      resources :resources
  end

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  # get '/galleries/:gallery_id/resources/:id',     to: 'resources#next',      as: 'next_gallery_resource'

  root 'galleries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    belongs_to :user
    has_many :resources, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
end

app/models/resource.rb
class Resource < ApplicationRecord
    belongs_to :gallery
    has_one_attached :file
    validates :name, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :galleries, dependent: :destroy
  has_one_attached :avatar
  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])            
      end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def create
    @gallery = current_user.galleries.create(gallery_params)
    # @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to @gallery
    else
      render 'new'
    end
  end

  def update
    @gallery = Gallery.find(params[:id])

    if @gallery.update(gallery_params)
      redirect_to @gallery
    else
      render 'edit'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    redirect_to galleries_path
  end

  private
    def gallery_params
      params.require(:gallery).permit(:title, :is_private)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :has_rights, except: :show

  def index
    @resources = Resource.all
  end

  def show
    # @resource = Resource.find(params[:id])

    @gallery = Gallery.find(params[:gallery_id])
    @resource = @gallery.resources.find(params[:id])
    # resources = @gallery.resources.order('resources.id ASC')
    # @resource = resources.find(params[:id])

    @next = @gallery.resources.where('resources.id > ?', @resource.id).first
    @prev = @gallery.resources.where('resources.id < ?', @resource.id).last
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @resource = @gallery.resources.new
  end

  def edit
    @gallery = Gallery.find(params[:gallery_id])
    @resource = Resource.find(params[:id])
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @resource = @gallery.resources.create(resource_params)

    if @resource.save
      redirect_to gallery_path(@gallery)
    else
      render 'new'
    end
  end

  def update
    @gallery = Gallery.find(params[:gallery_id])
    @resource = @gallery.resources.find(params[:id])

    if @resource.update(resource_params)
      redirect_to [@gallery, @resource]
    else
      render 'edit'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:gallery_id])

    @resource = @gallery.resources.find(params[:id])
    @resource.file.purge
    @resource.destroy
    redirect_to gallery_path(@gallery)
  end

  private
    def resource_params
      params.require(:resource).permit(:name, :description, :file)
    end

    def has_rights
      @gallery = Gallery.find(params[:gallery_id])

      # @resource = @gallery.resources.find(params[:id])
      # @resource = Resource.find(params[:id])
      if current_user != @gallery.user
          redirect_to galleries_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :has_rights, except: :show

  def index
      @users = User.all
  end

  def show
      @user = User.find_by_id(params[:id])
  end

  def update
      @user = User.find(params[:id])
      if @user.update_attributes(secure_params)
          redirect_to users_path, :notice => "User updated."
      else
          redirect_to users_path, :alert => "Unable to update user."
      end
  end

  private
      def has_rights
          if current_user.user?
              redirect_to galleries_path
          end
      end

      def secure_params
          params.require(:user).permit(:role)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/galleries/_form.html.erb
<%= form_with model: @gallery, local: true do |form| %>
  <div class="grid-container full">
    <div class="grid-x grid-margin-x">
      <div class="cell grid-x grid-padding-x">
        <div class="cell small-3">
          <%= form.label :title, :class => "text-right middle", :for => "gallery_name" %>
        </div>
        <div class="cell small-3">
          <%= form.text_field :title %>
        </div
      </div>
      <div class="cell grid-x grid-padding-x">
        <div class="small-3 cell">
          <%= form.label :is_private, :class => "text-right middle", :for => "gallery_is_private" %>
        </div>
        <div class="small-3 cell">
          <%= form.check_box :is_private %>
        </div>
      </div>
      <div class="cell grid-x grid-padding-x">
        <div class="cell small-3 small-offset-3">
          <%= form.submit 'Save', :class => "button" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/galleries/_gallery.html.erb
<% if !gallery.is_private? || (current_user == gallery.user) %>
  <div class="cell">
    <h5><%= gallery.title %></h5>
    <% if gallery.resources.blank? %>
      <br><%= link_to("Add media", gallery_path(gallery)) %>
    <% else %>
      <%= link_to gallery_path(gallery), :class => "thumbnail" do %>
          <div class="grid-x grid-margin-x small-up-2 medium-up-2 large-up-2">
              <% gallery.resources[0..3].each do |resource| %>
                <div class="cell small-2 gallery-cell">
                  <% if resource.file.attached? %>
                    <%#= image_tag resource.file.variant(resize_to_fill: [250, 250]), :class => "gallery-image" %>
                    <%= image_tag resource.file, :class => "gallery-image" %>
                  <% end %>
                </div>
              <% end %>
          </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Edit gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>All Galleries</h1>
<div class="grid-x grid-margin-x small-up-2 medium-up-4 large-up-4">
  <%= render @galleries %>
  <div class="cell grid-x grid-margin-x align-middle">
    <div class="cell text-center">
      <%= link_to("New gallery", new_gallery_path) %>
    </div>
  </div>
</div>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<div class="grid-x grid-margin-x">
  <div class="cell small-3">
    <%= link_to user_path(@gallery.user) do %>
      <strong>User:</strong>
      <%= @gallery.user.username %>
    <% end %>
  </div>
  <div class="cell">
    <h3><strong>Title:</strong><%= @gallery.title %></h3>
  </div>
  <div class="cell">
    <strong>Access:</strong>
    <% if @gallery.is_private %>
      <span>Gallery is private.</span>
    <% else %>
      <span>Gallery is open.</span>
    <% end %>
  </div>
  <div class="cell">
    <% if current_user == @gallery.user %>
      <%= link_to 'Edit', edit_gallery_path(@gallery), :class => "button" %>
      <%= link_to 'Delete Gallery', gallery_path(@gallery), method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %>
    <% end %>
  </div>
</div>


<h3 class="text-center">Resources</h3>
<div class="grid-x grid-margin-x small-up-2 medium-up-4 large-up-4">
  <%= render @gallery.resources %>
  <div class="cell grid-x grid-margin-x align-middle">
    <div class="cell text-center">
      <%= link_to('Add resource', new_gallery_resource_path(@gallery)) %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer grid-x grid-margin-x medium-margin-collapse small-up-2 medium-up-2 large-up-2">
  <div class="cell footer-left">
    Ruby on Rails
  </div>
  <div class="cell footer-right">
    test@test.com
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu="data-dropdown-menu">
        <li class="menu-text">Galleries App</li>
        <li><%= link_to("Galleries", galleries_path)%></li>
        <li>
          <% if !current_user.blank? and (current_user.admin? or current_user.moderator?) %>
            <%= link_to("Users", users_path) %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user) do %>
                <% if current_user.avatar.attached? %>
                  <%#= image_tag current_user.avatar.variant(resize_to_fill: [50, 50]), :class => "user-avatar" %>
                  <%= image_tag current_user.avatar, :class => "user-avatar" %>
                <% end %>
              <% end %>
            </li>
            <li><%= link_to(current_user.username, user_path(current_user)) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li><%= link_to('Login', new_user_session_path) %></li>
          <% end %>
      </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render partial: "/layouts/header" %>
    <section class="container">
      <%= yield %>
    </section>
    <%= render partial: "/layouts/footer" %>

  </body>
</html>

app/views/resources/_form.html.erb
<%#= form_with(model: [ @gallery, @gallery.resources.build ], local: true) do |form| %>
<%= form_with model: [ @gallery, @resource ], local: true do |form| %>
  <div class="grid-container full">
    <div class="grid-x grid-margin-x">
      <div class="cell grid-x grid-padding-x">
        <div class="cell small-3 small-offset-3">
          <%= form.label "Load file", :class => "button", :for => "fileUpload" %><br>
          <%= form.file_field :file, :class => "show-for-sr", :id => "fileUpload" %>
        </div>
      </div>
      <div class="cell grid-x grid-padding-x">
        <div class="small-3 cell">
          <%= form.label :name, :class => "text-right middle", :for => "resource_name" %>
        </div>
        <div class="small-3 cell">
          <%= form.text_field :name %>
        </div>
      </div>
      <div class="cell grid-x grid-padding-x">
        <div class="small-3 cell">
          <%= form.label :description, :class => "text-right middle", :for => "resource_description" %>
        </div>
        <div class="small-3 cell">
          <%= form.text_area :description %>
        </div>
      </div>
      <div class="cell grid-x grid-padding-x">
        <div class="cell small-3 small-offset-3">
          <%= form.submit 'Save', :class => "button" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div class="cell">
  <% if resource.file.attached? %>
    <div class="resource-thumbnail">

      <% if ['image/jpeg', 'image/gif', 'image/png', 'image/jpeg'].include? resource.file.content_type %>
        <%#= link_to(image_tag(resource.file.variant(resize_to_fill: [500, 500]), :class => "resource-preview"), gallery_resource_path(resource.gallery_id, resource), :class => "thumbnail") %>
        <%= link_to(image_tag(resource.file, :class => "resource-preview"), gallery_resource_path(resource.gallery_id, resource), :class => "thumbnail resource-thumbnail-image") %>
      <% else %>
        <%= link_to('show', gallery_resource_path(resource.gallery_id, resource), :class => "thumbnail") %>
      <% end %>
      <% if !resource.file.attached? %>
        <%= link_to('show', gallery_resource_path(resource.gallery_id, resource), :class => "thumbnail") %>
      <% end %>

    </div>
  <% end %>
</div>

app/views/resources/edit.html.erb
<h1>Edit resource</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_resource_path(@gallery, @resource) %>

app/views/resources/index.html.erb
<h2>All resources</h2>

<ul>
  <% @resources.each do |resource| %>
    <li>
      <%= resource.name %><br>
      <%= resource.description %><br>
      <%= link_to('show', gallery_resource_path(resource.gallery, resource)) %>
      <%= link_to(resource.gallery.title, gallery_path(resource.gallery)) %>
    </li>
  <% end %>
</ul>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_path(@resource.gallery) %>

app/views/resources/show.html.erb
<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell grid-x">
      <div class="cell small-2">
        <%= link_to user_path(@resource.gallery.user) do %>
          <strong>User: </strong><%= @resource.gallery.user.username %>
        <% end %>
      </div>
      <div class="cell">
        <%= link_to gallery_path(@resource.gallery) do %>
        <h3><strong>Gallery: </strong><%= @resource.gallery.title %></h3>
        <% end %>
      </div>
      <div class="cell small-2 medium-4">
        <h3><strong>Name: </strong><%= @resource.name %></h3>
      </div>
    </div>
    <div class="cell">
        <% if not @prev.nil? %>
          <%= link_to('Prev', gallery_resource_path(@resource.gallery, @prev)) %>
        <% end %>
        <% if not @next.nil? %>
          <%= link_to('Next', gallery_resource_path(@resource.gallery, @next)) %>
        <% end %>
      <div class="cell text-center"><hr>
        <% if @resource.file.attached? %>
        <image src="<%= (url_for(@resource.file)) %>">
          <% end %><hr>
      </div>
    </div>
    <div class="cell">
      <% if current_user == @resource.gallery.user %>
        <%= link_to('Edit Resource', edit_gallery_resource_path(@resource.gallery, @resource), :class => "button") %>
        <%= link_to 'Delete Resource', [@resource.gallery, @resource], method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %>
      <% end %>
    </div>
    <div class="cell text">
      <h3>Description:</h3>
      <%= @resource.description %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= link_to 'Current User', user_path(current_user) %>
<table class="stack text-center">
  <tr>
    <th>Email</th>
    <th>Username</th>
    <th>Role</th>
    <th colspan="2"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.username %></td>
      <td>
          <% if current_user.admin? %>
              <%= form_for(user) do |f| %>
              <div class="grid-x grid-padding-x small-offset-3 align-middle">
                <div class="small-4 cell">
                  <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
                </div>
                <div class="small-2 cell">
                  <%= f.submit 'Change Role', :class => 'button' %>
                </div>
              </div>
              <% end %>
          <% else %>
              <%= user.role %>
          <% end %>
      </td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="grid-container">
  <div class="grid-x grid-margin-x">
    <div class="cell text-center">
      <% if @user.avatar.attached? %>
        <image src="<%=(url_for(@user.avatar))%>">
      <% end %>
    </div>

    <div class="cell text-center">
      <span>Username: <%= @user.username %></span>
    </div>
    <div class="cell text-center">
      <span>Role: <%= @user.role %></span>
    </div>
    <% if current_user == @user || current_user.moderator? %>
      <div class="cell text-center">
        <span>Email: <%= @user.email %></span>
      </div>
      <div class="cell text-center">
        <%= link_to 'Edit Profile',edit_user_registration_path %>
      </div>
    <% end %>
  </div>

  <div class="cell">
    <div class="grid-x grid-margin-x small-up-2 medium-up-4 large-up-4">
      <%= render @user.galleries %>
    </div>
  </div>
</div>